version: "3.8"
services:
  mysql-standalone:
    image: mysql/mysql-server:8.0.13
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employee
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_HOST="%"
    ports:
      - 3306:3306

  Viewjs:
    image: vuejs_linked_java:latest
    ports:
        - 8080:8080
    build:
        context: ./
        dockerfile: D:\VScode_workspace_practice\employee_desc
    depends_on:
        - DockerTesting
  
  DockerTesting:
    image: employeecrud:latest
    ports:
      - 7000:7000
    restart: on-failure
    build:
      context: ./
      dockerfile: C:\Users\pa7nfa\Downloads\EmployeeCrud
    depends_on:
      - mysql-standalone  